- name: Update apt cache
  apt:
    update_cache: yes

- name: Install base packages
  apt:
    name:
      - git
      - unzip
      - curl
      - composer
      - mariadb-server
      - nginx
      - php
      - php-cli
      - php-fpm
      - php-xml
      - php-mbstring
      - php-json
      - php-bcmath
      - php-curl
      - php-mysql
      - php-zip
      - php-gd
      - php-intl
      - php-tokenizer
      - nodejs
      - npm
    state: present
  retries: 5
  delay: 5
  register: apt_done
  until: apt_done is succeeded

- name: Install NVM
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  args:
    creates: ~/.nvm

- name: Load NVM and install Node.js 20
  shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install 20
  args:
    executable: /bin/bash
    