- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create MySQL Database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present

- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_username  }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    state: present