- name: Create systemd override directory for MariaDB
  file: 
    path: /etc/systemd/system/mariadb.service.d
    state: directory
    mode: '0755'

- name: Disable namespace protections for MariaDB
  copy: 
    dest: /etc/systemd/system/mariadb.service.d/override.conf
    content: |
      [Service]
      PrivateTmp=false
      ProtectHome=false
      ProtectSystem=false
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Re-exec systemd to apply namespace changes
  command: systemctl daemon-reexec

- name: Restart MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: Ensure PyMySQL is installed for Ansible MySQL modules
  ansible.builtin.apt:
    name: python3-pymysql
    state: present

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create MySQL Database
  community.mysql.mysql_db:
    name: "{{ mysql_database }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_username  }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_database }}.*:ALL"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock